### ISSUE TITLE
WANTED: Icon Designer

### ISSUE THREAD

**Issue by 6alileo** [Retro-Arena/RetroArena-Setup#12]
We are looking for an icon designer to redesign all of our Settings Menu icon set located here:
https://github.com/Retro-Arena/RetroArena-Setup/tree/master/scriptmodules/supplementary/settingsmenu/icons

Please reply here or visit our Discord at https://discord.gg/zPy8Psx if interested.

**Comment by Liontek1985** [comment]
hello guys

if you want a designer for icons i can help you

reference see here 

tekfolder for retropie
https://github.com/Liontek1985/RetroPie-tekfolder/tree/master/tekfolder_png/icons

or my runcommand launching collection
https://github.com/Liontek1985/es-tekcommand

if you want to integrate in ORA have you my agreement

**Comment by 6alileo** [comment]
Can you join our discord @Liontek1985

https://discord.gg/zPy8Psx

**Comment by Liontek1985** [comment]
i have installed the app and joined the group

**Comment by 6alileo** [comment]
What's your username?

________________________________

**Comment by Liontek1985** [comment]
Liontek1985#7367
