### ISSUE TITLE
HELP WANTED - Wii U and Switch Pro Controllers

### ISSUE THREAD

**Issue by slappymcphee** [Retro-Arena/RetroArena-Setup#16]
The Retro Arena is current running kernel 3.10.x Ubuntu 16.04 LTS Minimal on the Odroid XU4. Per our understanding support for the Wii U and Switch Pro controller variants require kernel 3.12. We are looking for a resource to back port support for these controllers on our build. A bounty will be provided. We have limited funds however we can at least provide something.

**Comment by rfrayer420** [comment]
dragonrise usb gamepad would be nice as well. I wonder if RA can be compiled on 18.04?

**Comment by adiastra** [comment]
This is still an issue.

**Comment by adiastra** [comment]
From what I can tell this requires 3.11+ 
https://github.com/dvdhrm/xwiimote/issues/31

Thats why I am using Batocera now :(

**Comment by JoeyHSchmoe** [comment]
Wii U controller work fine using the May Flash Wireless Wii U Pro Controller Adapter for PC USB.  Home Button doesn't work when you are pairing multiple and no rumble feature.
