### ISSUE TITLE
RetroArenaSetup Menus OK and CANCEL buttons are reveresed

### ISSUE THREAD

**Issue by chewvodka** [Retro-Arena/RetroArena-Setup#18]
When you're navigating around ES and RetroArch, you get pretty well accustomed to using `A` (3:00 position) as the OK button, and `B` (6:00 position) as the CANCEL button.  However, with the new 3.03 build Thera, these buttons have been reversed.  You now press `B` to access menus, navigate, and click "OK" and `A` to cancel, go back or up a menu.  This is really confusing.  Any chance it can be fixed?

**Comment by 6alileo** [comment]
You will need to run RetroArena-Setup then proceed to:

`Manage packages > Manage core packages > emulationstation > Configurations/Options > Swap A/B Buttons in ES`

**Comment by chewvodka** [comment]
I actually fixed the problem in RetroArch by manually changing the setting:
`Settings > Input > Menu Swap OK & Cancel Buttons` and turning it **OFF**
