### ISSUE TITLE
Daphne error

### ISSUE THREAD

**Issue by Jmanning6600** [Retro-Arena/RetroArena-Setup#2]
Daphne games wont load.daphne    retropie error    /opt/retroarena/emulators/daphne/daphne.sh: line 10: /opt/retropie/emulators/daphne/daphne.bin: No such file or directory. 

The fix edit the above file to say retroarena and reinstall daphne.

**Comment by 6alileo** [comment]
Fixed by editing the file. Once verified on next image, I will close.

**Comment by 6alileo** [comment]
Fixed by removing the emulator and reinstalling from source.

**Comment by 6alileo** [comment]
The new RC3 image has the emulator working now but Neon has indicated that it runs in windowed mode. Can you see if there's a specific config setting for it to be full screen? It should be in the RC2 image. Will keep this open.

**Comment by 6alileo** [comment]
Rom config related issue. Closing.
