### ISSUE TITLE
Add themes

### ISSUE THREAD

**Issue by Jmanning6600** [Retro-Arena/RetroArena-Setup#20]
We need to add  hursty super sweet and fabuloso to the the theme repo. Also add hurstys super cool 100 themes in randomizer to replace what's currently there.

**Comment by 6alileo** [comment]
Every theme Hursty has is in HurstyThemes while the 3 Odroid exclusive themes remain in ESthemes.

**Comment by 6alileo** [comment]
https://github.com/Retro-Arena/RetroArena-Setup/commit/de85185d1a7cd761aa14f017d0dce617f29508ce

**Comment by Jmanning6600** [comment]
The problem is the themes in the randomizer are not RA ready so they will
be incomplete. The new cool themes are All RA ready.
