### ISSUE TITLE
Write speed problem with large NTFS formatted USB HDD 

### ISSUE THREAD

**Issue by LordGimbli** [Retro-Arena/RetroArena-Setup#22]
I got a transfer speed of 13.5-15kb/s when syncing the roms folder to a NTFS formatted 5tb USB HDD with stock settings! Next I tried to format ext.4 but that USB hdd was not found by TheRA. Could of course be cuz I used Paragons "Linux File Systems for Windows"!

With NTFS: 
When removing the sync option from MOUNTOPTIONS="sync,noexec,nodev,noatime,nodiratime,uid=1000,gid=1000" the transfer speed increased to 10mb/s which still is kind of slow for a USB3.0 device.

With my last change I tripled the transfer speed to 30mb/s:
MOUNTOPTIONS="noatime,async,big_writes,uid=1000,gid=1000"

**Comment by 6alileo** [comment]
Good for you. I'm not sure what ramifications changing those mount options. The settings we have are the safest from losing data. We will not change our settings but thank you for the information.
