### ISSUE TITLE
Xbox One controller

### ISSUE THREAD

**Issue by DaverJ007** [Retro-Arena/RetroArena-Setup#23]
Can't get Xbox One controller to be recognized by the base ODROID build.  It vibrates upon boot, but the controller never lights up, nor is recognized during the setting up controllers.

btw, couldn't get to https://retroarena.org.uk/forum/

**Comment by DaverJ007** [comment]
Forgot to mention, this is a wired USB connection, which works fine on my Raspberry Pi builds.

**Comment by 6alileo** [comment]
We just purchased a wired controller for our dev to test and figure out. Did you install the xbox driver by any chance?

**Comment by DaverJ007** [comment]
Yes, I installed the Xbox driver package, but to no affect for the Xbox One controller via USB connection.  When setting up a controller, the Xbox One controller isn't recognized, even if connected via USB.

Also, I tried the Nintendo Switch Pro controller, which was recognized by controller setup as a gamepad connected, but no button pushes were read and couldn't proceed with controller setup.

The Sony PS4 Dual Shock 4 works great via USB connection, as does the Mayflash Arcade Stick F300 Elite.

**Comment by DaverJ007** [comment]
Also, THANKS for looking into this!

**Comment by 6alileo** [comment]
I'm sorry we did not purchase an Xbox One, it was a 360. When we have the funds we'll try to get one for testing.

**Comment by 6alileo** [comment]
@DaverJ007 - might want to check this out

https://github.com/atar-axis/xpadneo

**Comment by 6alileo** [comment]
A kernel update for the XU4 should fix this issue.
