### ISSUE TITLE
USB Directory Sync

### ISSUE THREAD

**Issue by slappymcphee** [Retro-Arena/RetroArena-Setup#24]
We have community members posting that the ability to plug a USB stick or HDD and having the directory structure automatically populate as in previous versions is no longer working. If this is to be the default behavior moving forward we need to provide this information to the community or else we need to change the behavior so that it mimics what the previous feature was. This also ties into the ability to add roms/media from a USB stick to your EMMC/SD Card.

**Comment by 6alileo** [comment]
The retropie solution auto starts rsync when an empty drive is plugged in. It does not work on the XU4 or if it did, it would not give the user a way to identify its progress. The current solution copies the roms folder into the usb drive or the other option is to generate the `retroarena/roms` path.

Syncing the other way around is not that simple. There has to be checks between each drive to ensure the contents of the USB drive is less than free space of the SD card. I don't believe this is an issue but more of a luxury at this point. The user has several options to transfer their files via SSH and samba.
