### ISSUE TITLE
Joy2key does not work

### ISSUE THREAD

**Issue by sikotik** [Retro-Arena/RetroArena-Setup#25]
I haven't had a chance to dig into the issue but it appears that joy2key doesn't even start on this board.

**Comment by Stephenm64** [comment]
Going to look into this a little bit today.

**Comment by Stephenm64** [comment]
Looking into the function of joy2key it was depending on a missing interface: /dev/input/jsX

Enabled two options in kernel and the issue is resolved:
INPUT_JOYDEV [=y]
JOYSTICK_ANALOG [=y]

Closing.
