### ISSUE TITLE
Issue with running MAME cores

### ISSUE THREAD

**Issue by treaves** [Retro-Arena/RetroArena-Setup#28]
This referee to an XU4 running the official image.

When using libretro-mame as the MAME emulator, running any ROM fails.  This is true with the version provided as part of the latest image, as well when building from source.  I do not believe the issue is with MAME itself, but the TheRA scripts that run it.

Basically the failure is that the system is not finding the driver/system.  Why I beige the issue is with TheRA is because the system not found always matches the folder the ROM's are locate in.  For example:

```
[libretro INFO] Starting game:/home/pigaming/RetroArena/roms/mame-libretro/pacma
n.zip
[libretro INFO] Game name: pacman, Game description: Pac-Man (Midway)
[libretro ERROR] System not found: mame-libretro
[libretro WARN] Driver mame-libretro not found -1
[libretro INFO] Creating frontend for game: pacman
[libretro INFO] Softlists: 0
Unknown system 'mame-libretro'
```
when the ROM's are in the default mame-libretro folder, and when they are in the arcade folder, we get:
```
[libretro ERROR] System not found: arcade
[libretro WARN] Driver arcade not found -1
[libretro INFO] Creating frontend for game: galaga
[libretro INFO] Softlists: 0
Unknown system 'arcade'
```

I have create an issue with MAME, but, it would seem to be a parsing issue of the path.

**Comment by sikotik** [comment]
I've looked at the emulators.cfg for all instances of libretro mame cores. This should not be happening and i could not reproduce it on my system.  I'll leave the issue open so when we resolve it we'll have an answer if it crops up again.
