### ISSUE TITLE
Reicast issue

### ISSUE THREAD

**Issue by Jmanning6600** [Retro-Arena/RetroArena-Setup#3]
Neon has found another retropie that needs to be changed for the standalone reicast.

/opt/retroarena/emulators/reicast/bin/reicast.sh: line 17: /opt/retropie/lib/inifuncs.sh: No such file or directory

**Comment by 6alileo** [comment]
There were a lot of references so I did a remove and reinstall. Once verified on next image, I will close.

**Comment by 6alileo** [comment]
RC3 fixed this issue. Closing.
