### ISSUE TITLE
USB audio toggle feature

### ISSUE THREAD

**Issue by Stephenm64** [Retro-Arena/RetroArena-Setup#30]
Creation of a helper script to toggle the system wide use of a external audio device such as a usb sound card.

**Comment by slappymcphee** [comment]
bumping for the heck of it

**Comment by camatthew** [comment]
bump

**Comment by blisstik** [comment]
Done on master branch for XU4 only. Will need testing for RP64 as that is also 32bit OS. It does not work for the N2.
