### ISSUE TITLE
Add ddr game port such as stepmania or pydance

### ISSUE THREAD

**Issue by camatthew** [Retro-Arena/RetroArena-Setup#33]
Suggestion for xu4

**Comment by slappymcphee** [comment]
we can look into it however we have also moved to a quarterly release schedule therefore it is not something that will be *resolved* at the moment. thank you for the suggestion.

**Comment by NeonLightning** [comment]
i tried installing them previously but i couldn't get stepmania to install and pydance requires x i believe
