### ISSUE TITLE
Megadrive Genesis logo swap

### ISSUE THREAD

**Issue by keno21176** [Retro-Arena/RetroArena-Setup#34]
Prior versions had a toolbox option to run a script to swap menu graphic logo from genesis to megadrive and also PC engine to Turbografx.  Cannot find in latest version.

**Comment by NeonLightning** [comment]
our solution is we have both folders display incase you want separate regions games

**Comment by keno21176** [comment]
Ah of course, makes sense. Not sure why I had them in megadrive folder anyway, maybe was a holdover from my retropie days lol
Thanks
Ken
