### ISSUE TITLE
Error when trying to update the RetroArena script

### ISSUE THREAD

**Issue by Cee123** [Retro-Arena/RetroArena-Setup#37]
What is the issue?
Whenever I try to update the RetroArena script, I get the following error message - error running git pull -1

How can we reproduce the issue from a fresh image?
Not really sure how as it was a sudden issue. It could be the result of something I've done.

Provide hardware details below:
Odroid XU4, with Odroid Wifi module 3
https://kamami.com/usb-wifi-adapters-for-odroid-c2/205179-odroid-wifi-module-3.html
RetroArena (I'll have to get back to you on the version)
Not really sure what other information I could provide

**Comment by blisstik** [comment]
You will need to SSH in order to run this command as pigaming user

`cd RetroArena-Setup && git reset --hard && git clean -f -d && cd -`

**Comment by Cee123** [comment]
OK I'm not really sure I've done this properly. 

It says HEAD is now at 574e983 rapidjson-dev

**Comment by Cee123** [comment]
What exactly do you mean when you say "SSH"? I'm not really sure I've done this properly. But this is what I've done and it did something, but I'm not really sure what.

![IMAG0289](https://user-images.githubusercontent.com/43462099/61960391-ee38e600-aff7-11e9-960b-9c609fca5e31.jpg)

I'm guessing I did it wrong though because when I update the setup script, it still gives me the error message. It does say that it's updated. But the error shows up immediately after.

![IMAG0290](https://user-images.githubusercontent.com/43462099/61960474-1e808480-aff8-11e9-9a67-a74edaac7292.jpg)

**Comment by blisstik** [comment]
I would start from a new image. Not sure of the issue there.

________________________________

**Comment by Cee123** [comment]
Yeah I might have to. I'll just do that after backing everything up and transferring to a new image.
