### ISSUE TITLE
OGST Menu Settings Don't Work

### ISSUE THREAD

**Issue by darth-g00b** [Retro-Arena/RetroArena-Setup#38]
What is the issue? (unsure if correct area to post this issue)
OGST menu settings don't influence image on LED screen.
The option to turn the screen on and off are working, however any other option results in a black LED screen.

How can we reproduce the issue from a fresh image?
Current Version of theRA (not beta) flashed via Etcher onto 128gig SD.
Connect Odroid to internet via Ethernet cable.
Load games via network.
Use Selph's Scrapper to source potential images for Roms.
Change Emulation Station theme
Change OGST settings to Selph's Scrapper Marquees. (Or anything else. only option that works is turn LED screen off. Any other options displays nothing but turns the screen on.)

Provide hardware details below:
Odroid XU4 - Model with Fan.
128 gig samsung micro SD.
OGST case

**Comment by blisstik** [comment]
When you enable OGST settings, there's a menu to choose which option, then it will show on the screen the path of the image its expecting. Check this for more information:

https://github.com/Retro-Arena/RetroArena-Setup/blob/master/scriptmodules/supplementary/caseconfig.sh

**Comment by darth-g00b** [comment]
Thanks for the info. However, all the files are in there correct location and I still can't seem to get the setting to work. I can still only turn the screen off and on.

I'm currently trying to get option 10 Selph's Marquee working. And currently have the files under roms/SYSTEM/images/ROM-marquee.png

Anymore assistance would be fantastic. :)

**Comment by blisstik** [comment]
Sounds like a hardware problem. Even without selecting any option, you should have default images showing up on the screen.

**Comment by darth-g00b** [comment]
Was hoping that wouldn't be the case because the case and board are brand new. I'll do some more testing with different software to see if I can get it to display anything at all. Thanks for you assistance!
